name: Daily Kalimati Vegetables Price Scraper

on:
  schedule:
    - cron: '15 2 * * *'  # ⏰ 8:00 AM Nepal time
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node scrape-kalimati.js
